#!/bin/bash

CONF_DIR='/etc/dockerconf/'

pass_edit ()
{
  echo 'Edit password'
  rm -f /etc/passwd
  cp -f ${CONF_DIR}passwd /etc/
  rm -f /etc/shadow
  cp -f ${CONF_DIR}shadow /etc/
  rm -f /etc/group
  cp -f ${CONF_DIR}group /etc/
}

pass_save ()
{
  echo 'Save password'
  rm -f ${CONF_DIR}shadow
  mv /etc/shadow ${CONF_DIR}
  ln -s ${CONF_DIR}shadow /etc/shadow

  rm -f ${CONF_DIR}passwd
  mv /etc/passwd ${CONF_DIR}
  ln -s ${CONF_DIR}passwd /etc/passwd

  rm -f ${CONF_DIR}group
  mv /etc/group ${CONF_DIR}
  ln -s ${CONF_DIR}group /etc/group
}

echo 'Start type: '${TYPE_START}
df -h
ls -ld ${CONF_DIR}*

case ${TYPE_START} in
  sshd ) rm -f /etc/passwd
         rm -f /etc/shadow
         rm -f /etc/group
         ln -s ${CONF_DIR}shadow /etc/shadow
         ln -s ${CONF_DIR}passwd /etc/passwd
         ln -s ${CONF_DIR}group /etc/group 
         /usr/sbin/sshd -D
     ;;
  create )
         echo 'Create profile'
         groupadd sftp -g 3000
         echo "root:${ROOT_PASSWORD}" | chpasswd         
         pass_save
     ;;
  createuser )
        pass_edit
        useradd ${FTP_USER} --no-create-home -G sftp
        mkdir /home/${FTP_USER}
        chown ${FTP_USER}.${FTP_USER} /home/${FTP_USER}
        chmod 700 /home/${FTP_USER}
        echo "${FTP_USER}:${FTP_PASSWORD}" | chpasswd
        pass_save
     ;;
  deluser )  
        pass_edit
        userdel ${FTP_USER}
        pass_save        
     ;;
  setpassword )
        pass_edit 
        echo "${FTP_USER}:${FTP_PASSWORD}" | chpasswd
        pass_save
     ;;
  rootpassword ) echo "root:${ROOT_PASSWORD}" | chpasswd
     ;;
  * ) echo ${TYPE_START}
     ;;
esac
