#!/bin/bash

pass_edit ()
{
  rm -f /etc/passwd
  cp -f /home/conf/passwd /etc/
  rm -f /etc/shadow
  cp -f /home/conf/shadow /etc/
  rm -f /etc/group
  cp -f /home/conf/group /etc/
}

pass_save ()
{
  rm -f /home/conf/shadow
  mv /etc/shadow /home/conf/
  ln -s /home/conf/shadow /etc/shadow

  rm -f /home/conf/passwd
  mv /etc/passwd /home/conf/
  ln -s /home/conf/passwd /etc/passwd

  rm -f /home/conf/group
  mv /etc/group /home/conf/
  ln -s /home/conf/group /etc/group
}

case ${TYPE_START} in
  sshd ) rm -f /etc/passwd
         rm -f /etc/shadow
         rm -f /etc/group
         ln -s /home/conf/shadow /etc/shadow
         ln -s /home/conf/passwd /etc/passwd
         ln -s /home/conf/group /etc/group 
         /usr/sbin/sshd -D
     ;;
  create )
         groupadd sftp -g 3000
         useradd ${FTP_USER} -u 3000 -G sftp
         chmod 700 /home/${FTP_USER}
         echo "${FTP_USER}:${FTP_PASSWORD}" | chpasswd
         echo "root:${ROOT_PASSWORD}" | chpasswd         
         mkdir /home/conf
         pass_save
     ;;
  createuser )
        pass_edit
        useradd ${FTP_USER} -G sftp
        chmod 700 /home/${FTP_USER}
        echo "${FTP_USER}:${FTP_PASSWORD}" | chpasswd
        pass_save
     ;;
  deluser )  
        pass_edit
        userdel ${FTP_USER}
        pass_save        
     ;;
  setpassword )
        pass_edit 
        echo "${FTP_USER}:${FTP_PASSWORD}" | chpasswd
        pass_save
     ;;
  rootpassword ) echo "root:${ROOT_PASSWORD}" | chpasswd
     ;;
  * ) echo ${TYPE_START}
     ;;
esac
